In [72]:
import requests
import pandas as pd

In [73]:
# URl b√°sica
base_url = "https://prep2024.ine.mx/publicacion/nacional/assets/presidencia/entidad/{}.json"

# Dataframe en blanco
all_data = pd.DataFrame()

In [74]:

# Iterar por las 32 entidades
for id_entidad in range(1, 33):
    # url
    url = base_url.format(id_entidad)
    
    
    response = requests.get(url)
    data = response.json()

    # Extraer datos de los partidos
    votes_data = data['votosPartidosPoliticos']['votos']
    entidad = data['entidad']

    # Listas para almacenar votos por partido
    votos_pan = []
    votos_pri = []
    votos_prd = []
    votos_pvem = []
    votos_pt = []
    votos_mc = []
    votos_morena = []
    votos_no_reg = []
    votos_nulos = []

    # Extraer datos
    for vote in votes_data:
        if vote['partido'] == '1':
            votos_pan.append(vote['votos'])
        if vote['partido'] == '2':
            votos_pri.append(vote['votos'])
        if vote['partido'] == '3':
            votos_prd.append(vote['votos'])
        if vote['partido'] == '4':
            votos_pvem.append(vote['votos'])
        if vote['partido'] == '5':
            votos_pt.append(vote['votos'])
        if vote['partido'] == '6':
            votos_mc.append(vote['votos'])
        if vote['partido'] == '8':
            votos_morena.append(vote['votos'])
        if vote['partido'] == '61':
            votos_no_reg.append(vote['votos'])
        if vote['partido'] == '62':
            votos_nulos.append(vote['votos'])

    # Crear dataframe
    df = pd.DataFrame({
        'pan': votos_pan,
        'pri': votos_pri,
        'prd': votos_prd,
        'pvem': votos_pvem,
        'pt': votos_pt,
        'mc': votos_mc,
        'morena': votos_morena,
        'no_reg': votos_no_reg,
        'nulos': votos_nulos,
        'entidad': entidad
    })

    # Eliminar comas
    df = df.replace(',', '', regex=True).astype(int)

    # Pegar el dataframe al dataframe general
    all_data = pd.concat([all_data, df], ignore_index=True)

all_data

,pan,pri,prd,pvem,pt,mc,morena,no_reg,nulos,entidad
0,99773,17118,5867,9381,8933,23883,90627,947,5802,1
1,38469,12012,3032,14397,14807,24374,128455,504,5620,2
2,12290,2309,783,2945,3757,4385,21827,63,1068,3
3,2655,3667,386,2433,2872,9243,24701,61,976,4
4,62988,295284,15160,46188,46621,53313,404597,728,20155,5
5,17958,18096,2096,8031,6086,17226,52684,259,2458,6
6,17730,20951,4053,43052,22374,20563,113120,343,10602,7
7,93004,29985,5903,16690,18656,34731,158257,539,8288,8
8,444174,127831,41036,90137,85370,137598,732990,2965,30035,9
9,41052,51217,5350,15560,21055,23176,127100,322,5833,10
10,304871,45365,10459,41040,30773,92197,334081,1389,18366,11
11,11966,30357,14095,31267,23269,20213,175637,399,9179,12
12,36539,44818,5516,27504,36928,49116,220099,654,9309,13
13,223528,97957,15952,46014,36805,160101,314668,2023,20632,14
14,367833,395814,45131,187186,170370,327629,1487704,4092,63252,15
15,96747,51188,24163,39182,47498,67739,206415,1149,17651,16
16,21904,9359,2877,12173,11472,19319,69446,175,3037,17
17,4474,2774,632,3700,2531,5123,16896,31,888,18
18,198641,89124,12240,47426,45123,140426,244969,1679,14043,19
19,24550,35953,7263,41848,46275,30311,236003,465,10463,20
20,75982,22811,5268,35482,29029,42948,186945,581,10117,21
21,134064,21309,5669,23108,19086,36186,151215,1005,8259,22
22,37549,13885,3824,49669,15223,23394,146945,469,6126,23
23,58713,25769,6056,84168,14673,37854,89782,541,8283,24
24,32089,31962,3829,16254,13282,20948,142197,620,5640,25
25,22861,20388,2587,12398,11293,16680,95423,261,3707,26
26,7203,8571,11204,14750,16510,14400,168423,310,5641,27
27,117370,24599,5109,32057,25160,53786,290745,726,11403,28
28,8754,8197,1704,11195,12619,17245,60123,114,2594,29
29,119854,67620,13870,53066,39308,72430,470556,1013,18183,30
30,39772,8015,982,6715,6822,10247,61274,165,2399,31
31,26898,33834,7437,14211,15966,41616,82119,429,6190,32